### PR TITLE
docs: readme: --save -> --save-dev

### PR DESCRIPTION
**Pull request by coderaiser**
Changed the way `remark` npm updates `package.json`: `dependencies` -> `devDependencies`.

### CODE REVIEW

**Comment by wooorm** [comment]
I don’t think remark is necessarily a dev-dependency though? 🤔

**Comment by coderaiser** [comment]
@wooorm why not? `eslint` is `devDependency` in most cases, and when we talk about `cli`-version it is always `devDependency` or global installation because the only place where it used is `npm-scripts`.

**Comment by wooorm** [comment]
Oh I misread, thought this was on the remark readme. Ok, makes sense!

**Review by wooorm — APPROVED** [review]

**Comment by wooorm** [comment]
thanks!

**Pull request merged**
