### PR TITLE
feat: Implemented mdash style rule

### PR DESCRIPTION
**Pull request by alexandrtovmach**
Implemented simple rule for mdash style.

### CODE REVIEW

**Comment by alexandrtovmach** [comment]
@wooorm Could you take a look?

**Comment by wooorm** [comment]
Hey Alexandr!

Interesting rule! I think it makes a great case for an external rule though, [like these](https://github.com/remarkjs/remark-lint#list-of-external-rules), that way you can maintain it the way you like, while still allowing others to use it.

I’d also suggest to use a different algorithm:

First, a tip, typically you shouldn‘t walk the tree multiple times. You can instead pass multiple types to `visit`. Here’s an excerpt from the [underlying utility](https://github.com/syntax-tree/unist-util-visit-parents/blob/master/readme.md#api):

> Walking the tree is an intensive task. Make use of the return values of the visitor when possible. Instead of walking a tree multiple times with different tests, walk it once without a test, and use unist-util-is to check if a node matches a test, and then perform different operations.

In this case, you should be able to `visit(tree, 'text')`. Also only gets the values in headings and paragraphs. And it ignores `inlineCode` and the like! (that is one of the benefits of having a syntax tree instead of regexing a file).

Lastly, I suggest making positional information map to exactly the place the dash happened. You can use `node.position.start.offset` of the text node, plus the index of the mdash in `node.value`, to get the absolute offset in the file the offset occurred at.
Finally, you can turn that absolute offset into a proper position object with:

```js
  var position = location(file).toPosition
  // ...
  file.message(reason, position(thatAbsoluteOffset))
```

**Comment by alexandrtovmach** [comment]
@wooorm Thank you for great advice, makes sense. I'll update the code and publish it as external package

**Comment by wooorm** [comment]
Cool, good luck! And open a PR to add it do the docs here when it’s done!

**Pull request closed without merging**
